# conf/default.yaml

# ... (既存の model, data, optim_args, scheduler_args などの設定) ...
defaults:
 - _self_
 - data: wlasl100
 - model: postnorm_transformer
 - search_space: step1

epochs: 1500
batch_size: 16
label_smooting: 0.05
accum_iter: 16
gradient_clip: 10.0

optim_type: adamw
optim_args:
    lr: 1.0e-3
    momentum: 0.99
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1.0e-8

scheduler_type: cosine
scheduler_args:
    min_lr: 1.0e-5
    warmup_epoch: 5
    warmup_lr_init: 1.0e-4

seed: 42
num_workers: 8
pin_memory: true

topk: [1,5,10]

# Optunaによる最適化の基本設定
optuna:
  n_trials: 100                     # 試行回数
  monitor: "valid_accuracy_PI@01"  # 監視するメトリクス (LightningModelのlog_dictキー)
  direction: "maximize"            # "maximize" (最大化) or "minimize" (最小化)
  log_dir: "logs/optuna_study"     # Optuna用のログ保存先
  storage: "sqlite:///optuna_history.db"
  study_name: null

  pruner:
    enabled: true
    pruner_args:
      n_startup_trials: 10
      n_warmup_steps: 300


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
